# permissions for end users to edit stewardcontrolplanes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: stewardcontrolplane-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cluster-api-control-plane-provider-steward
    app.kubernetes.io/part-of: cluster-api-control-plane-provider-steward
    app.kubernetes.io/managed-by: kustomize
  name: stewardcontrolplane-editor-role
rules:
- apiGroups:
  - controlplane.cluster.x-k8s.io
  resources:
  - stewardcontrolplanes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - controlplane.cluster.x-k8s.io
  resources:
  - stewardcontrolplanes/status
  verbs:
  - get
