## Append samples you want in your CSV to this file as resources ##
resources:
- controlplane_v1alpha1_stewardcontrolplane.yaml
- controlplane_v1alpha1_stewardcontrolplanetemplate.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
