# Copyright 2025 The Butler Authors.
# SPDX-License-Identifier: Apache-2.0
name: CI

on:
  push:
    branches:
      - '**'
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - 'Makefile'
      - 'config/**'
  pull_request:
    branches: [main, master]
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - 'Makefile'
      - 'config/**'

permissions:
  contents: read
  pull-requests: read

jobs:
  commit_lint:
    name: Lint Commits
    runs-on: ubuntu-22.04
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v6

  golangci:
    name: Lint Go
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.0.2
          args: --timeout 5m --config .golangci.yml

  test:
    name: Unit Tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Run tests
        run: CGO_ENABLED=0 go test -v ./...

  diff:
    name: Check Generated Files
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Install tools
        run: |
          make controller-gen
          make kustomize
      - name: Generate manifests
        run: |
          make generate
          make manifests
      - name: Generate release manifests
        run: make release
        env:
          CGO_ENABLED: 0
      - name: Check for untracked changes
        run: |
          if [[ $(git diff | wc -l) -gt 0 ]]; then
            echo ">>> Untracked generated files have not been committed"
            git --no-pager diff
            exit 1
          fi
      - name: Check for untracked files
        run: |
          if [[ -n "$(git ls-files --others --exclude-standard 2>/dev/null)" ]]; then
            echo ">>> New untracked files detected"
            git ls-files --others --exclude-standard
            exit 1
          fi

  build:
    name: Build
    runs-on: ubuntu-22.04
    needs: [golangci, test, diff]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Build
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o bin/manager ./main.go
      - name: Build ARM64
        run: CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o bin/manager-arm64 ./main.go
